# Generated by Django 5.0 on 2023-12-29 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=100)),
                ("dni", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "lugar_de_origen",
                    models.CharField(
                        choices=[
                            ("amazonas", "Amazonas"),
                            ("ancash", "Ancash"),
                            ("apurimac", "Apurimac"),
                            ("arequipa", "Arequipa"),
                            ("ayacucho", "Ayacucho"),
                            ("cajamarca", "Cajamarca"),
                            ("callao", "Callao"),
                            ("cusco", "Cusco"),
                            ("huancavelica", "Huancavelica"),
                            ("huanuco", "Huánuco"),
                            ("ica", "Ica"),
                            ("junin", "Junín"),
                            ("la_libertad", "La Libertad"),
                            ("lambayeque", "Lambayeque"),
                            ("lima", "Lima"),
                            ("loreto", "Loreto"),
                            ("madre_de_dios", "Madre De Dios"),
                            ("moquegua", "Moquegua"),
                            ("pasco", "Pasco"),
                            ("piura", "Piura"),
                            ("puno", "Puno"),
                            ("san_martin", "San Martin"),
                            ("tacna", "Tacna"),
                            ("tumbes", "Tumbes"),
                            ("ucayali", "Ucayali"),
                            ("otro", "Otro"),
                        ],
                        default="ica",
                        max_length=100,
                    ),
                ),
                ("celular", models.CharField(max_length=15)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "origen_del_prospecto",
                    models.CharField(
                        choices=[
                            ("pagina_web", "Página web"),
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("tiktok", "TikTok"),
                            ("meet", "Meet"),
                            ("contacto_referencial", "Contacto Referencial"),
                            ("marketplace", "Marketplace"),
                            ("publicidad_pagada", "Publicidad Pagada"),
                            ("otros", "Otros"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "seguimiento",
                    models.CharField(
                        choices=[
                            ("informacion_enviada", "Información Enviada"),
                            ("en_negociacion", "cliente interesado"),
                            ("pendiente_por_llamar", "Pendiente por Llamar"),
                            ("no_contesta", "No Contesta"),
                            ("no_interesado", "No Interesado"),
                            ("por_enviar_deposito", "Por Enviar Depósito"),
                            ("venta_exitoso", "Venta Exitosa"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "motivo_de_compra",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("inversion", "Inversión"),
                            ("vivienda", "Vivienda"),
                            ("otro", "Otro"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("fecha_de_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_de_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "asesor_coordinador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Coordinador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("es_asesor", models.BooleanField(default=False)),
                (
                    "asesores",
                    models.ManyToManyField(
                        related_name="coordinador_asesores", to="clientes.asesor"
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="asesor",
            name="grupo_coordinador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="clientes.coordinador"
            ),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="profiles"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField()),
                ("fecha_de_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_de_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clientes.cliente",
                    ),
                ),
            ],
        ),
    ]
